[package]
name = "rsmediakeys"
version = "0.1.1"
authors = ["Bas Dusee <basdusee@hotmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["mpd", "laptopkeys"]

[dependencies]
notify-rust = "4.2.2"

[dependencies.clap]
version = "~2.33"
default-features = false
